# -*- coding: utf-8 -*-
"""Titanic_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bHfI8X7IyVbuWb6Uu5L2__Zgh8w57YFY
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open('model_titanic.pkl', 'rb') as file:
    model = pickle.load(file)

st.title("Titanic Survival Prediction App")

st.write("Please enter the passenger details:")

# Create input fields
pclass = st.selectbox("Passenger Class (Pclass)", [1, 2, 3])
sex = st.selectbox("Sex", ['male', 'female'])
age = st.number_input("Age", min_value=0, max_value=100, value=25)
sibsp = st.number_input("Number of Siblings/Spouses Aboard (SibSp)", min_value=0, max_value=10, value=0)
parch = st.number_input("Number of Parents/Children Aboard (Parch)", min_value=0, max_value=10, value=0)
fare = st.number_input("Passenger Fare", min_value=0.0, value=30.0)
embarked = st.selectbox("Port of Embarkation (Embarked)", ['C', 'Q', 'S'])

# Map categorical variables
sex = 1 if sex == 'male' else 0
embarked_mapping = {'C': 0, 'Q': 1, 'S': 2}
embarked = embarked_mapping[embarked]

# Make prediction
if st.button('Predict'):
    input_features = np.array([[pclass, sex, age, sibsp, parch, fare, embarked]])
    prediction = model.predict(input_features)
    if prediction[0] == 1:
        st.success("The passenger would have survived!")
    else:
        st.error("The passenger would not have survived.")

